[package]
name = "tuf"
version = "0.0.1"
authors = [ "heartsucker <heartsucker@autistici.org>" ]
description = "Library for The Update Framework (TUF)"
homepage = "https://github.com/heartsucker/tuf"
repository = "https://github.com/heartsucker/tuf"
documentation = "https://docs.rs/tuf"
readme = "README.md"
license = "MIT"
keywords = [ "security" ]
categories = [ "cryptography" ]

[badges]
travis-ci = { repository = "heartsucker/tuf", branch = "master" }

[lib]
name = "tuf"
path = "./src/lib.rs"

[dependencies]
chrono = { version = "0.3", features = [ "serde" ] }
rustc-serialize = "0.3"
url = "1.4"
